name: 'Escape - GraphQL Security'
author: 'Escape-Technologies'
description: 'Secure your application using Escape.tech'

inputs:
  application_id:
    description: 'The id of your application'
    required: true
  api_key:
    description: 'Your escape api key'
    required: true
  timeout:
    description: 'Maximum blocking time for a CI/CD run'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ESCAPE_APPLICATION_ID: ${{ inputs.application_id }}
    ESCAPE_API_KEY: ${{ inputs.api_key }}
    TIMEOUT: ${{ inputs.timeout }}

branding:
  icon: 'check'
  color: 'white'
