name: "Escape - API Security"
author: "Escape-Technologies"
description: "Secure your application using Escape.tech"

inputs:
  application_id:
    description: "The id of your application"
    required: true
  api_key:
    description: "Your escape api key"
    required: true
  timeout:
    description: "Maximum blocking time for a CI/CD run"
    required: false
  configuration_override:
    description: "Partial JSON configuration for the scan"
    required: false
  configuration_override_path:
    description: "Path to JSON file containing a partial configuration for the scan"
    required: false
  schema_file:
    description: "Path to the schema file"
    required: false
  introspection_file:
    description: "Path to the introspection response file"
    required: false
  fail_on_severities:
    description: "A csv-delimited list of severities to fail on, can be HIGH, MEDIUM, LOW, INFO"
    default: 'HIGH'
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    ESCAPE_APPLICATION_ID: ${{ inputs.application_id }}
    ESCAPE_API_KEY: ${{ inputs.api_key }}
    TIMEOUT: ${{ inputs.timeout }}
    CONFIGURATION_OVERRIDE: ${{ inputs.configuration_override }}
    CONFIGURATION_OVERRIDE_PATH: ${{ inputs.configuration_override_path }}
    SCHEMA_FILE: ${{ inputs.schema_file }}
    SCHEMA_URL: ${{ inputs.schema_url }}
    INTROSPECTION_FILE: ${{ inputs.introspection_file }}
    FAIL_ON_SEVERITIES: ${{ inputs.fail_on_severities }}
    FAIL_ON_COMPLIANCE: ${{ inputs.fail_on_compliance }}

branding:
  icon: "check"
  color: "white"
